version: "3"

vars:
  PACKAGES:
    sh: go list ./...

tasks:
  default:
    desc: List all the available tasks.
    cmds:
      - task --list
    silent: true

  init:
    desc: Install required dependencies (macOS).
    cmds:
      - brew install go-task/tap/go-task
      - brew upgrade go-task/tap/go-task
      - brew install golangci-lint
      - brew upgrade golangci-lint

  fmt:
    desc: Run "go fmt" on all Go packages.
    cmds:
      - echo 'Formatting codes...'
      - go fmt {{catLines .PACKAGES}}
    silent: true

  lint:
    desc: Run "golang-ci lint run".
    cmds:
      - echo 'Linting source code...'
      - golangci-lint run
    silent: true

  tidy:
    desc: Run "go mod tidy" and "go mod verify".
    cmds:
      - echo 'Tidying and verifying module dependencies...'
      - go mod tidy
      - go mod verify
    silent: true

  vet:
    desc: Run "go vet" on all Go packages.
    cmds:
      - echo 'Vetting codes...'
      - go vet {{catLines .PACKAGES}}
    silent: true

  test:
    desc: Run all tests.
    cmds:
      - echo 'Testing codes...'
      - go test -coverprofile=coverage.out {{catLines .PACKAGES}}
    silent: true

  test:coverage:
    desc: Run unit tests and show test coverage information.
    cmds:
      - go tool cover -html=coverage.out

  audit:
    desc: Audits Go codes.
    deps:
      - fmt
      - tidy
    silent: true
